#ifndef PWANTOOLS_ENUMS_H
#define PWANTOOLS_ENUMS_H

namespace pwan
{
    enum p_returnValue { P_OK, P_ERROR, P_NO_ARGUMENTS, P_NOT_FOUND };
    enum p_img_keyevent { NEXTIMAGE, PREVIMAGE, FIRSTIMAGE, LASTIMAGE, QUIT, SCROLLDOWN, SCROLLUP, SCROLLLEFT, SCROLLRIGHT, ZOOMIN, ZOOMOUT, FULLSCREEN, SCALE };
}

#endif
